### ISSUE TITLE
ImportError when running tests in django 1.8+

### ISSUE THREAD

**Issue by fritz-k** [mathiasertl/django-hashers-passlib#3]
Running the test suite `from django.contrib.auth.hashers import load_hashers` throws an `ImportError`

```
running test
Traceback (most recent call last):
  File "setup.py", line 122, in <module>
    "Topic :: System :: Systems Administration :: Authentication/Directory",
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 73, in run
    from test import test_hashers
  File "/home/fritz/projekte/django-hashers-passlib/test/test_hashers.py", line 31, in <module>
    from django.contrib.auth.hashers import load_hashers
ImportError: cannot import name 'load_hashers'
```

Looks like `load_hashers` was removed in django 1.8.

**Comment by mathiasertl** [comment]
Thank you very much for your report(s). I will release a new version compatible with Django 1.8+ very soon.

**Comment by fritz-k** [comment]
Thanks!
